### ISSUE TITLE
Problem with running TMC2209

### ISSUE THREAD

**Issue by tomasz90** [daniel-frenkel/book#1]
Am I right that below connections from your book are unnecessery using esp32 uart? 
<img width="674" alt="Screenshot 2024-07-28 at 14 43 03" src="https://github.com/user-attachments/assets/226f5731-6f36-40f1-97c0-33c68ab8ab88">
I don't know why, but I fired my driver...
This stallguard demo is working? Because before I burned my driver I was only getting 0s even if tried to spin the shaft?

**Comment by daniel-frenkel** [comment]
Those are needed is using the STEP/DIR with UART. However, you can use the built-in pulse generator via UART, in which case those will not be needed. I personally prefer the pulse generator to offload the task from the IC, so I don't use STEP/DIR much. But it's good to know how to use it, which is why I have it here for the demo.
